name: Gen Account Pro

concurrency:
  group: create-account-pro

on:
  repository_dispatch:
    types: [ Create account pro ]
permissions:
  contents: write
  actions: write

jobs:
  build:
    if: ${{ !github.event.issue.pull_request }}
    runs-on: self-hosted

    steps:
      - name: bash-version
        run: echo "::add-mask::${{ github.event.client_payload.hardwardid }}"

      - uses: ztzzxyz/dotnet-reactor-run-action@licensemgr
        with:
          master_key: ${{ secrets.REACTOR_MKEY }}
          license_days: ${{ github.event.client_payload.licensedays }}
          hardware_id: ${{ github.event.client_payload.hardwardid }}
          output_path: ${{ github.workspace }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.client_payload.order_sn }}
          path: hb.license

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 30
          keep_minimum_runs: 100
