name: Gen Account By Gitee Compent

on:
  workflow_dispatch:
  schedule:
    - cron: '50 3,9,15 * * *'

env:
  TZ: Asia/Shanghai

permissions:
  actions: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Gen Account
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: |
          python gen_license.py
      - name: Push to gitee
        run: |
          git config --global user.name 'Github Action'
          git config --global user.email '5175709+xuzhengtong@user.noreply.gitee.com'
          if [[ -n $(git status --porcelain) ]]; then
              git add . && git commit -m "Auto commit by Github action"
          fi
          git remote add gitee https://${{ secrets.GITEE_USER }}:${{ secrets.GITEE_TOKEN }}@gitee.com/hearthstone-hearthbuddy/Hearthbuddy-account.git
          git push -f gitee main
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 3
          keep_minimum_runs: 3
